title: Kanishka Parankusham | AI & Systems Engineer
description: Portfolio of Kanishka Parankusham. Specializing in High-Performance Computing, Artificial Intelligence, and Systems Architecture.
author: Kanishka Parankusham
theme: jekyll-theme-hacker
plugins:
  - jekyll-seo-tag